
DO $$
DECLARE
    VAL INT := 17;
BEGIN
    IF VAL>=1 AND VAL<=10 THEN
        RAISE NOTICE 'Your VALUE IS % and RANGE IS BETWEEN 1 TO 10', VAL;
    ELSIF VAL>10 AND VAL<=20 THEN
        RAISE NOTICE 'Your VALUE IS % and RANGE IS BETWEEN 10 TO 20', VAL;
    ELSIF VAL>20 AND VAL<=30 THEN
        RAISE NOTICE 'Your VALUE IS % and RANGE IS BETWEEN 20 TO 30', VAL;
    ELSE 
        RAISE NOTICE 'Your VALUE IS % AND GREATER THAN 30', VAL;
    END IF;
    END;
$$;
